
services:
  pptools:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: pptools
    ports:
      - 8002:5000
    volumes:
      - projects:/app/wsgi/projects

volumes:
  projects:
